<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * mPDF Configuration for CodeIgniter 3
 *
 * Place this file in application/config/mpdf.php
 */

$config['mpdf'] = [
	// Page settings
	'mode' => 'utf-8',                    // Document encoding
	'format' => 'A4',                     // Page format (A4, A3, Letter, etc.)
	'orientation' => 'P',                 // P for Portrait, L for Landscape
	'margin_left' => 15,                  // Left margin in mm
	'margin_right' => 15,                 // Right margin in mm
	'margin_top' => 16,                   // Top margin in mm
	'margin_bottom' => 16,                // Bottom margin in mm
	'margin_header' => 9,                 // Header margin in mm
	'margin_footer' => 9,                 // Footer margin in mm

	// Document information
	'title' => 'PDF Document',            // Document title
	'author' => 'Your Application Name',  // Document author
	'subject' => 'Generated PDF',         // Document subject
	'creator' => 'mPDF Generator',        // Document creator
	'keywords' => 'pdf, codeigniter',     // Document keywords

	// Font settings
	'default_font' => 'dejavusans',       // Default font family
	'default_font_size' => 12,            // Default font size

	// Header settings
	'header_enable' => true,              // Enable header
	'header_title' => 'My Application',   // Header title
	'header_string' => '',                // Additional header text
	'header_logo' => '',                  // Path to header logo
	'header_logo_width' => 30,            // Logo width in mm
	'header_logo_height' => 0,            // Logo height in mm (0 = auto)

	// Footer settings
	'footer_enable' => true,              // Enable footer
	'footer_text' => 'Generated by My App', // Footer text
	'footer_show_page' => true,           // Show page numbers in footer

	// Protection settings
	'protection' => false,                // Enable PDF protection
	'user_password' => '',                // User password
	'owner_password' => '',               // Owner password
	'permissions' => [],                  // Permissions array

	// Language and script settings
	'auto_language_detection' => true,    // Auto language detection
	'auto_script_to_lang' => true,        // Auto script to language
	'baseScript' => 1,                    // Base script
	'autoVietnamese' => true,             // Auto Vietnamese
	'autoArabic' => true,                 // Auto Arabic

	// Watermark settings
	'watermark' => '',                    // Watermark text or image path
	'watermark_alpha' => 0.2,             // Watermark transparency
	'show_watermark_image' => false,      // Show image watermark
	'show_watermark_text' => false,       // Show text watermark
];
